In [1]:
from pymongo import MongoClient

# Connecting to MongoDB and accessing the database and collection
URL = f"mongodb+srv://eli-vang:k8aQiTt6wrrqSe@cluster0.1lvb0s3.mongodb.net/final_project"
client = MongoClient(URL)
db = client["final_project"]
collection = db["savant"]

In [2]:
import pandas as pd

# Fetching all documents from the collection and converting to a DataFrame
results = collection.find({})
df = pd.DataFrame(list(results))

df.head()

,_id,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,batter,pitcher,events,...,batter_days_until_next_game,api_break_z_with_gravity,api_break_x_arm,api_break_x_batter_in,arm_angle,attack_angle,attack_direction,swing_path_tilt,intercept_ball_minus_batter_pos_x_inches,intercept_ball_minus_batter_pos_y_inches
0,69d3c54eef428760b51381cf,SL,11/1/2025,85.9,-3.1,5.64,"Scherzer, Max",500743,453286,single,...,,3.13,-0.2,-0.2,31.5,-5.823739,-17.027322,29.582052,32.972714,44.206122
1,69d3c54eef428760b51381d0,SL,11/1/2025,85.4,-3.11,5.55,"Scherzer, Max",500743,453286,,...,,2.86,-0.29,-0.29,33.7,,,,,
2,69d3c54eef428760b51381d1,CH,11/1/2025,84.8,-3.3,5.36,"Scherzer, Max",571771,453286,,...,,2.82,0.79,0.79,27.4,,,,,
3,69d3c54eef428760b51381d2,CU,11/1/2025,73.2,-3.02,5.75,"Scherzer, Max",571771,453286,strikeout,...,,5.25,-1.04,-1.04,40.4,2.410072,30.857094,31.03147,44.98723,21.325831
4,69d3c54eef428760b51381d3,SL,11/1/2025,88.7,-1.92,5.99,"Ohtani, Shohei",666182,660271,home_run,...,,2.64,-0.1,-0.1,40.8,3.753491,-9.95437,31.73651,37.886817,30.395348

In [3]:
df = df.replace("", pd.NA)

In [17]:

for column in df.columns:
    null_percentage = df[column].isna().sum() / len(df) * 100
    
    print(f"Column: {column}, Null Percentage: {null_percentage:.2f}%")

Column: _id, Null Percentage: 0.00%
Column: pitch_type, Null Percentage: 0.67%
Column: game_date, Null Percentage: 0.00%
Column: release_speed, Null Percentage: 0.67%
Column: release_pos_x, Null Percentage: 0.67%
Column: release_pos_z, Null Percentage: 0.67%
Column: player_name, Null Percentage: 0.00%
Column: batter, Null Percentage: 0.00%
Column: pitcher, Null Percentage: 0.00%
Column: events, Null Percentage: 74.59%
Column: description, Null Percentage: 0.00%
Column: spin_dir, Null Percentage: 100.00%
Column: spin_rate_deprecated, Null Percentage: 100.00%
Column: break_angle_deprecated, Null Percentage: 100.00%
Column: break_length_deprecated, Null Percentage: 100.00%
Column: zone, Null Percentage: 0.67%
Column: des, Null Percentage: 0.00%
Column: game_type, Null Percentage: 0.00%
Column: stand, Null Percentage: 0.00%
Column: p_throws, Null Percentage: 0.00%
Column: home_team, Null Percentage: 0.00%
Column: away_team, Null Percentage: 0.00%
Column: type, Null Percentage: 0.00%
Column: hit_location, Null Percentage: 77.98%
Column: bb_type, Null Percentage: 83.47%
Column: balls, Null Percentage: 0.00%
Column: strikes, Null Percentage: 0.00%
Column: game_year, Null Percentage: 0.00%
Column: pfx_x, Null Percentage: 0.67%
Column: pfx_z, Null Percentage: 0.67%
Column: plate_x, Null Percentage: 0.67%
Column: plate_z, Null Percentage: 0.67%
Column: on_3b, Null Percentage: 91.35%
Column: on_2b, Null Percentage: 81.96%
Column: on_1b, Null Percentage: 69.54%
Column: outs_when_up, Null Percentage: 0.00%
Column: inning, Null Percentage: 0.00%
Column: inning_topbot, Null Percentage: 0.00%
Column: hc_x, Null Percentage: 83.47%
Column: hc_y, Null Percentage: 83.47%
Column: tfs_deprecated, Null Percentage: 100.00%
Column: tfs_zulu_deprecated, Null Percentage: 100.00%
Column: umpire, Null Percentage: 100.00%
Column: sv_id, Null Percentage: 100.00%
Column: vx0, Null Percentage: 0.67%
Column: vy0, Null Percentage: 0.67%
Column: vz0, Null Percentage: 0.67%
Column: ax, Null Percentage: 0.67%
Column: ay, Null Percentage: 0.67%
Column: az, Null Percentage: 0.67%
Column: sz_top, Null Percentage: 0.67%
Column: sz_bot, Null Percentage: 0.67%
Column: hit_distance_sc, Null Percentage: 67.70%
Column: launch_speed, Null Percentage: 67.74%
Column: launch_angle, Null Percentage: 67.69%
Column: effective_speed, Null Percentage: 0.68%
Column: release_spin_rate, Null Percentage: 0.70%
Column: release_extension, Null Percentage: 0.67%
Column: game_pk, Null Percentage: 0.00%
Column: fielder_2, Null Percentage: 0.00%
Column: fielder_3, Null Percentage: 0.00%
Column: fielder_4, Null Percentage: 0.00%
Column: fielder_5, Null Percentage: 0.00%
Column: fielder_6, Null Percentage: 0.00%
Column: fielder_7, Null Percentage: 0.00%
Column: fielder_8, Null Percentage: 0.00%
Column: fielder_9, Null Percentage: 0.00%
Column: release_pos_y, Null Percentage: 0.67%
Column: estimated_ba_using_speedangle, Null Percentage: 83.54%
Column: estimated_woba_using_speedangle, Null Percentage: 74.97%
Column: woba_value, Null Percentage: 74.59%
Column: woba_denom, Null Percentage: 74.66%
Column: babip_value, Null Percentage: 74.59%
Column: iso_value, Null Percentage: 74.59%
Column: launch_speed_angle, Null Percentage: 83.54%
Column: at_bat_number, Null Percentage: 0.00%
Column: pitch_number, Null Percentage: 0.00%
Column: pitch_name, Null Percentage: 0.67%
Column: home_score, Null Percentage: 0.00%
Column: away_score, Null Percentage: 0.00%
Column: bat_score, Null Percentage: 0.00%
Column: fld_score, Null Percentage: 0.00%
Column: post_away_score, Null Percentage: 0.00%
Column: post_home_score, Null Percentage: 0.00%
Column: post_bat_score, Null Percentage: 0.00%
Column: post_fld_score, Null Percentage: 0.00%
Column: if_fielding_alignment, Null Percentage: 0.68%
Column: of_fielding_alignment, Null Percentage: 0.68%
Column: spin_axis, Null Percentage: 0.70%
Column: delta_home_win_exp, Null Percentage: 0.00%
Column: delta_run_exp, Null Percentage: 0.67%
Column: bat_speed, Null Percentage: 54.84%
Column: swing_length, Null Percentage: 54.84%
Column: estimated_slg_using_speedangle, Null Percentage: 83.54%
Column: delta_pitcher_run_exp, Null Percentage: 0.67%
Column: hyper_speed, Null Percentage: 67.56%
Column: home_score_diff, Null Percentage: 0.00%
Column: bat_score_diff, Null Percentage: 0.00%
Column: home_win_exp, Null Percentage: 0.00%
Column: bat_win_exp, Null Percentage: 0.00%
Column: age_pit_legacy, Null Percentage: 0.00%
Column: age_bat_legacy, Null Percentage: 0.00%
Column: age_pit, Null Percentage: 0.00%
Column: age_bat, Null Percentage: 0.00%
Column: n_thruorder_pitcher, Null Percentage: 0.00%
Column: n_priorpa_thisgame_player_at_bat, Null Percentage: 0.00%
Column: pitcher_days_since_prev_game, Null Percentage: 0.57%
Column: batter_days_since_prev_game, Null Percentage: 0.09%
Column: pitcher_days_until_next_game, Null Percentage: 48.71%
Column: batter_days_until_next_game, Null Percentage: 22.12%
Column: api_break_z_with_gravity, Null Percentage: 0.67%
Column: api_break_x_arm, Null Percentage: 0.67%
Column: api_break_x_batter_in, Null Percentage: 0.67%
Column: arm_angle, Null Percentage: 0.73%
Column: attack_angle, Null Percentage: 54.84%
Column: attack_direction, Null Percentage: 54.84%
Column: swing_path_tilt, Null Percentage: 54.84%
Column: intercept_ball_minus_batter_pos_x_inches, Null Percentage: 54.91%
Column: intercept_ball_minus_batter_pos_y_inches, Null Percentage: 54.91%

In [4]:
# converting on_1b - on_3b to boolean
df['on_1b'] = df['on_1b'].notna().astype(int)
df['on_2b'] = df['on_2b'].notna().astype(int)
df['on_3b'] = df['on_3b'].notna().astype(int)

In [5]:
# Important features
features = [
    # Player context
    "pitcher",
    "p_throws",
    "stand",

    # Count
    "balls",
    "strikes",

    # Game state
    "outs_when_up",
    "inning",
    "inning_topbot",

    # Base runners (binary)
    "on_1b",
    "on_2b",
    "on_3b",

    # Optional context
    "home_score_diff",
    "n_thruorder_pitcher",

    # Potential features
    "release_speed",
    "release_spin_rate",
    "spin_axis"
]

In [22]:
ml_df = df[features].copy()

In [ ]:
# ml_df.head()

,pitcher,p_throws,stand,balls,strikes,outs_when_up,inning,inning_topbot,on_1b,on_2b,on_3b,home_score_diff,n_thruorder_pitcher,release_speed,release_spin_rate,spin_axis
0,453286,R,R,0,1,1,5,Top,0,0,0,2,2,85.9,2371,165
1,453286,R,R,0,0,1,5,Top,0,0,0,2,2,85.4,2400,144
2,453286,R,R,1,2,0,5,Top,0,0,0,2,2,84.8,1279,243
3,453286,R,R,2,2,0,5,Top,0,0,0,2,2,73.2,2638,56
4,660271,R,R,0,0,1,3,Bot,1,0,1,0,2,88.7,2727,80

In [26]:
# ml_df['p_throws'].value_counts()
# ml_df['stand'].value_counts()
# ml_df['inning_topbot'].value_counts()

In [23]:
# One hot encoding categorical features
ml_df = pd.get_dummies(ml_df, columns=['p_throws', 'stand', 'inning_topbot'], drop_first=True)
ml_df['p_throws_R'] = ml_df['p_throws_R'].astype(int)
ml_df['stand_R'] = ml_df['stand_R'].astype(int)
ml_df['inning_topbot_Top'] = ml_df['inning_topbot_Top'].astype(int)

In [25]:
for col in ml_df.columns:
    print(f"{col}: {sum(ml_df[col].isna()) / len(ml_df) * 100:.2f}% null values")

pitcher: 0.00% null values
balls: 0.00% null values
strikes: 0.00% null values
outs_when_up: 0.00% null values
inning: 0.00% null values
on_1b: 0.00% null values
on_2b: 0.00% null values
on_3b: 0.00% null values
home_score_diff: 0.00% null values
n_thruorder_pitcher: 0.00% null values
release_speed: 0.67% null values
release_spin_rate: 0.70% null values
spin_axis: 0.70% null values
p_throws_R: 0.00% null values
stand_R: 0.00% null values
inning_topbot_Top: 0.00% null values

In [ ]:
# filling null values with median for numeric features based on pitcher
cols_to_fill = ['release_speed', 'release_spin_rate', 'spin_axis']
for col in cols_to_fill:
    ml_df[col] = ml_df.groupby('pitcher')[col].transform(lambda x: x.fillna(x.median()))

C:\Users\vanget\AppData\Local\Temp\ipykernel_22332\1776289855.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  ml_df[col] = ml_df.groupby('pitcher')[col].transform(lambda x: x.fillna(x.median()))
C:\Users\vanget\AppData\Local\Temp\ipykernel_22332\1776289855.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  ml_df[col] = ml_df.groupby('pitcher')[col].transform(lambda x: x.fillna(x.median()))
C:\Users\vanget\AppData\Local\Temp\ipykernel_22332\1776289855.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  ml_df[col] = ml_df.groupby('pitcher')[col].transform(lambda x: x.fillna(x.median()))
C:\Users\vanget\AppData\Local\Temp\ipykernel_22332\1776289855.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  ml_df[col] = ml_df.groupby('pitcher')[col].transform(lambda x: x.fillna(x.median()))
C:\Users\vanget\AppData\Local\Temp\ipykernel_22332\1776289855.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  ml_df[col] = ml_df.groupby('pitcher')[col].transform(lambda x: x.fillna(x.median()))
C:\Users\vanget\AppData\Local\Temp\ipykernel_22332\1776289855.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  ml_df[col] = ml_df.groupby('pitcher')[col].transform(lambda x: x.fillna(x.median()))
C:\Users\vanget\AppData\Local\Temp\ipykernel_22332\1776289855.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  ml_df[col] = ml_df.groupby('pitcher')[col].transform(lambda x: x.fillna(x.median()))
C:\Users\vanget\AppData\Local\Temp\ipykernel_22332\1776289855.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  ml_df[col] = ml_df.groupby('pitcher')[col].transform(lambda x: x.fillna(x.median()))
C:\Users\vanget\AppData\Local\Temp\ipykernel_22332\1776289855.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  ml_df[col] = ml_df.groupby('pitcher')[col].transform(lambda x: x.fillna(x.median()))
C:\Users\vanget\AppData\Local\Temp\ipykernel_22332\1776289855.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  ml_df[col] = ml_df.groupby('pitcher')[col].transform(lambda x: x.fillna(x.median()))
C:\Users\vanget\AppData\Local\Temp\ipykernel_22332\1776289855.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  ml_df[col] = ml_df.groupby('pitcher')[col].transform(lambda x: x.fillna(x.median()))
C:\Users\vanget\AppData\Local\Temp\ipykernel_22332\1776289855.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  ml_df[col] = ml_df.groupby('pitcher')[col].transform(lambda x: x.fillna(x.median()))
C:\Users\vanget\AppData\Local\Temp\ipykernel_22332\1776289855.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  ml_df[col] = ml_df.groupby('pitcher')[col].transform(lambda x: x.fillna(x.median()))
C:\Users\vanget\AppData\Local\Temp\ipykernel_22332\1776289855.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  ml_df[col] = ml_df.groupby('pitcher')[col].transform(lambda x: x.fillna(x.median()))
C:\Users\vanget\AppData\Local\Temp\ipykernel_22332\1776289855.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  ml_df[col] = ml_df.groupby('pitcher')[col].transform(lambda x: x.fillna(x.median()))
C:\Users\vanget\AppData\Local\Temp\ipykernel_22332\1776289855.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  ml_df[col] = ml_df.groupby('pitcher')[col].transform(lambda x: x.fillna(x.median()))
C:\Users\vanget\AppData\Local\Temp\ipykernel_22332\1776289855.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  ml_df[col] = ml_df.groupby('pitcher')[col].transform(lambda x: x.fillna(x.median()))
C:\Users\vanget\AppData\Local\Temp\ipykernel_22332\1776289855.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  ml_df[col] = ml_df.groupby('pitcher')[col].transform(lambda x: x.fillna(x.median()))
C:\Users\vanget\AppData\Local\Temp\ipykernel_22332\1776289855.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  ml_df[col] = ml_df.groupby('pitcher')[col].transform(lambda x: x.fillna(x.median()))
C:\Users\vanget\AppData\Local\Temp\ipykernel_22332\1776289855.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  ml_df[col] = ml_df.groupby('pitcher')[col].transform(lambda x: x.fillna(x.median()))
C:\Users\vanget\AppData\Local\Temp\ipykernel_22332\1776289855.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  ml_df[col] = ml_df.groupby('pitcher')[col].transform(lambda x: x.fillna(x.median()))
C:\Users\vanget\AppData\Local\Temp\ipykernel_22332\1776289855.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  ml_df[col] = ml_df.groupby('pitcher')[col].transform(lambda x: x.fillna(x.median()))
C:\Users\vanget\AppData\Local\Temp\ipykernel_22332\1776289855.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  ml_df[col] = ml_df.groupby('pitcher')[col].transform(lambda x: x.fillna(x.median()))
C:\Users\vanget\AppData\Local\Temp\ipykernel_22332\1776289855.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  ml_df[col] = ml_df.groupby('pitcher')[col].transform(lambda x: x.fillna(x.median()))
C:\Users\vanget\AppData\Local\Temp\ipykernel_22332\1776289855.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  ml_df[col] = ml_df.groupby('pitcher')[col].transform(lambda x: x.fillna(x.median()))
C:\Users\vanget\AppData\Local\Temp\ipykernel_22332\1776289855.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  ml_df[col] = ml_df.groupby('pitcher')[col].transform(lambda x: x.fillna(x.median()))
C:\Users\vanget\AppData\Local\Temp\ipykernel_22332\1776289855.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  ml_df[col] = ml_df.groupby('pitcher')[col].transform(lambda x: x.fillna(x.median()))
C:\Users\vanget\AppData\Local\Temp\ipykernel_22332\1776289855.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  ml_df[col] = ml_df.groupby('pitcher')[col].transform(lambda x: x.fillna(x.median()))
C:\Users\vanget\AppData\Local\Temp\ipykernel_22332\1776289855.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  ml_df[col] = ml_df.groupby('pitcher')[col].transform(lambda x: x.fillna(x.median()))
C:\Users\vanget\AppData\Local\Temp\ipykernel_22332\1776289855.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  ml_df[col] = ml_df.groupby('pitcher')[col].transform(lambda x: x.fillna(x.median()))
C:\Users\vanget\AppData\Local\Temp\ipykernel_22332\1776289855.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  ml_df[col] = ml_df.groupby('pitcher')[col].transform(lambda x: x.fillna(x.median()))
C:\Users\vanget\AppData\Local\Temp\ipykernel_22332\1776289855.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  ml_df[col] = ml_df.groupby('pitcher')[col].transform(lambda x: x.fillna(x.median()))
C:\Users\vanget\AppData\Local\Temp\ipykernel_22332\1776289855.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  ml_df[col] = ml_df.groupby('pitcher')[col].transform(lambda x: x.fillna(x.median()))
C:\Users\vanget\AppData\Local\Temp\ipykernel_22332\1776289855.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  ml_df[col] = ml_df.groupby('pitcher')[col].transform(lambda x: x.fillna(x.median()))
C:\Users\vanget\AppData\Local\Temp\ipykernel_22332\1776289855.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  ml_df[col] = ml_df.groupby('pitcher')[col].transform(lambda x: x.fillna(x.median()))
C:\Users\vanget\AppData\Local\Temp\ipykernel_22332\1776289855.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  ml_df[col] = ml_df.groupby('pitcher')[col].transform(lambda x: x.fillna(x.median()))
C:\Users\vanget\AppData\Local\Temp\ipykernel_22332\1776289855.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  ml_df[col] = ml_df.groupby('pitcher')[col].transform(lambda x: x.fillna(x.median()))
C:\Users\vanget\AppData\Local\Temp\ipykernel_22332\1776289855.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  ml_df[col] = ml_df.groupby('pitcher')[col].transform(lambda x: x.fillna(x.median()))
C:\Users\vanget\AppData\Local\Temp\ipykernel_22332\1776289855.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  ml_df[col] = ml_df.groupby('pitcher')[col].transform(lambda x: x.fillna(x.median()))
C:\Users\vanget\AppData\Local\Temp\ipykernel_22332\1776289855.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  ml_df[col] = ml_df.groupby('pitcher')[col].transform(lambda x: x.fillna(x.median()))
C:\Users\vanget\AppData\Local\Temp\ipykernel_22332\1776289855.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  ml_df[col] = ml_df.groupby('pitcher')[col].transform(lambda x: x.fillna(x.median()))
C:\Users\vanget\AppData\Local\Temp\ipykernel_22332\1776289855.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  ml_df[col] = ml_df.groupby('pitcher')[col].transform(lambda x: x.fillna(x.median()))
C:\Users\vanget\AppData\Local\Temp\ipykernel_22332\1776289855.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  ml_df[col] = ml_df.groupby('pitcher')[col].transform(lambda x: x.fillna(x.median()))
C:\Users\vanget\AppData\Local\Temp\ipykernel_22332\1776289855.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  ml_df[col] = ml_df.groupby('pitcher')[col].transform(lambda x: x.fillna(x.median()))
C:\Users\vanget\AppData\Local\Temp\ipykernel_22332\1776289855.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  ml_df[col] = ml_df.groupby('pitcher')[col].transform(lambda x: x.fillna(x.median()))
C:\Users\vanget\AppData\Local\Temp\ipykernel_22332\1776289855.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  ml_df[col] = ml_df.groupby('pitcher')[col].transform(lambda x: x.fillna(x.median()))
C:\Users\vanget\AppData\Local\Temp\ipykernel_22332\1776289855.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  ml_df[col] = ml_df.groupby('pitcher')[col].transform(lambda x: x.fillna(x.median()))

In [31]:
ml_df.columns

Index(['pitcher', 'balls', 'strikes', 'outs_when_up', 'inning', 'on_1b',
       'on_2b', 'on_3b', 'home_score_diff', 'n_thruorder_pitcher',
       'release_speed', 'release_spin_rate', 'spin_axis', 'p_throws_R',
       'stand_R', 'inning_topbot_Top'],
      dtype='object')

In [ ]:
# Once model is trained, we can save it using joblib
import joblib
joblib.dump(model, 'pitch_prediction_model.pkl')